language: java

services:
  - docker

jdk:
  - openjdk7
  - oraclejdk7  

before_install:
- docker pull postgres
- docker pull mysql
- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
X bundle exec rake test